baseURL = "http://linbarbell.com/"
languageCode = "en-us"
title = "Lin Barbell"

[params]
    author = "Emily Lin"
    description = "Emily Lin"

[[menu.main]]
    url = "/"
    name = "Home"
    identifier = "home"
    weight = 1

[[menu.main]]
    url = "/meets/"
    name = "Powerlifting"
    identifier = "meets"
    weight = 2

[[menu.main]]
    url = "/posts/"
    name = "Posts"
    identifier = "posts"
    weight = 3

[[menu.main]]
    url = "/wilks/"
    name = "Wilks"
    identifier = "wilks"
    weight = 4